apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: timoni-bundle-frontend
    namespace: timoni-system
    files:
      - bundle.cue
    options:
      disableNameSuffixHash: true
